[package]
name = "silo-core"
version = "0.1.0"
authors = ["Tyler Lafayette <tylerlafayette@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.3", features = ["full"] }
serde = "1"
serde_repr = "0.1"
actix = "0.10"
log = "0.4"
env_logger = "0.8.2"
pretty_env_logger = "0.4"
